#include "x87math.h"
#include <math.h>
#include <stdint.h>
#include "cpu.h"

static void push(struct cpu *cpu, double value) {
    cpu->fptop = (cpu->fptop - 1) & 7;
    cpu->st[cpu->fptop & 7] = value;
}

void hl_x86_x87_math(struct cpu *cpu) {
    double st0 = cpu->st[cpu->fptop & 7];
    double st1 = cpu->st[(cpu->fptop + 1) & 7];
    // x87 invalid operations deliver the QNaN indefinite with the sign bit SET (0xFFF8000000000000);
    // the host libm/ARM default NaN has it CLEAR. Only a GENERATED NaN may be stamped -- a NaN
    // propagated from an operand keeps that operand's sign -- so remember whether either input was
    // already a NaN and fix the sign of the (single) result slot afterwards. Same rule, and the same
    // "result NaN AND no input NaN" test, as emit_x87_dnan_post / emit_dnan_post in translate.c.
    int clean_in = !isnan(st0) && !isnan(st1);
    unsigned top_in = cpu->fptop;
    cpu->fpsw &= ~UINT64_C(0x4700);
    switch (cpu->x87_ea) {
    case X87_F2XM1: cpu->st[cpu->fptop & 7] = exp2(st0) - 1.0; break;
    case X87_FYL2X:
        cpu->st[(cpu->fptop + 1) & 7] = st1 * log2(st0);
        cpu->fptop = (cpu->fptop + 1) & 7;
        break;
    case X87_FPATAN:
        cpu->st[(cpu->fptop + 1) & 7] = atan2(st1, st0);
        cpu->fptop = (cpu->fptop + 1) & 7;
        break;
    case X87_FYL2XP1:
        cpu->st[(cpu->fptop + 1) & 7] = st1 * log2(st0 + 1.0);
        cpu->fptop = (cpu->fptop + 1) & 7;
        break;
    case X87_FPTAN:
        if (fabs(st0) >= 0x1p63) {
            cpu->fpsw |= UINT64_C(0x400);
            break;
        }
        cpu->st[cpu->fptop & 7] = tan(st0);
        push(cpu, 1.0);
        break;
    case X87_FSINCOS:
        if (fabs(st0) >= 0x1p63) {
            cpu->fpsw |= UINT64_C(0x400);
            break;
        }
        cpu->st[cpu->fptop & 7] = sin(st0);
        push(cpu, cos(st0));
        break;
    case X87_FSIN:
        if (fabs(st0) >= 0x1p63)
            cpu->fpsw |= UINT64_C(0x400);
        else
            cpu->st[cpu->fptop & 7] = sin(st0);
        break;
    case X87_FCOS:
        if (fabs(st0) >= 0x1p63)
            cpu->fpsw |= UINT64_C(0x400);
        else
            cpu->st[cpu->fptop & 7] = cos(st0);
        break;
    }
    if (clean_in) {
        // Neither input was a NaN, so any NaN now sitting in a slot this op could have written was
        // GENERATED by it -> give it x86's negative indefinite sign. The candidate slots are the two
        // the op reads/writes in place plus the slot a push created.
        unsigned slot[3] = {top_in & 7, (top_in + 1) & 7, cpu->fptop & 7};
        for (int i = 0; i < 3; i++) {
            double v = cpu->st[slot[i]];
            if (isnan(v) && !signbit(v)) cpu->st[slot[i]] = -v;
        }
    }
}
