#!/usr/bin/env bash
# Print the source manifest hash for the prebuilt crate archives.
#
# The crate at pkgs/rust/ does not compile src/: build.rs links the static
# archives committed under pkgs/rust/assets/lib/, and `cargo publish` ships
# those exact bytes. The manifest hash is a content digest of every C source
# and header that feeds those archives, so a changed .c file changes the hash
# and `tools/check_crate_archives.sh` can tell that the committed archives no
# longer correspond to the tree.
#
# Byte-comparing a rebuilt archive would be the stronger check, but the build
# is not reproducible across checkouts: the compiler records the absolute
# source directory (DW_AT_comp_dir) in every object, so two clones of the same
# commit at different paths produce different bytes. A content digest of the
# inputs has no such dependence.
#
# The file list comes from the Makefile (`print-archive-sources`, i.e.
# PRODUCTION_UNITY_DEPS) so it cannot drift from what the archive rules
# actually consume. It is a deliberate over-approximation: a macOS-only source
# change also invalidates the Linux archive. Both archives are regenerated by
# one command, so that costs nothing and never under-reports.
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"

# macOS ships `shasum`, Linux ships `sha256sum`; both print "<hash>  <path>".
sha256() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$@"
	else
		shasum -a 256 "$@"
	fi
}

sources=$(make -s print-archive-sources)
if [ -z "$sources" ]; then
	printf 'crate-archive-manifest: Makefile listed no archive sources\n' >&2
	exit 1
fi

# LC_ALL=C keeps the ordering locale-independent; the per-file digests make the
# hash sensitive to content, and the paths make it sensitive to files being
# added, removed or renamed.
files=()
while read -r file; do
	[ -n "$file" ] || continue
	files+=("$file")
done < <(printf '%s\n' "$sources" | tr ' ' '\n' | LC_ALL=C sort -u)

sha256 "${files[@]}" | sha256 | cut -d' ' -f1
