#!/usr/bin/env bash
# Emit the source-manifest stamp header force-included into every translation
# unit of the prebuilt crate archives.
#
# The manifest digest describes the C sources; the archive is a build artifact.
# Nothing tied the two together until this stamp: a refresh in an incremental
# build directory that failed to recompile a changed file produced an archive
# whose recorded manifest and SHA-256 both validated while its objects came
# from older sources.
#
# Every archive object carries the digest of the sources it was compiled
# against, so tools/check_crate_archives.sh can read the claim out of the
# archive bytes instead of trusting PROVENANCE.md. A stale object keeps the old
# digest and the gate sees two different stamps in one archive.
#
# The stamp is `static`, hence invisible to nm; the gate matches the byte string
# in the archive, which no linkage choice can hide.
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"

out=${1:?usage: gen_archive_stamp.sh <output-header>}

manifest=$(tools/crate_archive_manifest.sh)

tmp=$out.tmp.$$
trap 'rm -f "$tmp"' EXIT
{
	printf '/* generated by tools/gen_archive_stamp.sh -- do not edit */\n'
	printf '__attribute__((used)) static const char hl_archive_source_stamp[] =\n'
	printf '\t"HL-ARCHIVE-SOURCE-MANIFEST:%s";\n' "$manifest"
} >"$tmp"

# Rewrite only on change: the custom command reruns whenever any source
# changes, and CMake's Ninja rule restats, so an unchanged stamp must not
# recompile the whole archive.
if cmp -s "$tmp" "$out"; then
	rm -f "$tmp"
else
	mv -f "$tmp" "$out"
fi
